name: Cypress Tests

on: push
env:
  CYPRESS_users: ${{secrets.USERS}}
  CYPRESS_admin: ${{secrets.ADMIN}}
jobs:
  cypress-run:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --spec cypress\\integration\\examples\\Test3RadioCheckBoxDropDown.ts --browser=chrome
  